### ISSUE TITLE
When timer ends, switch is not turning off

### ISSUE THREAD

**Issue by tkundhi** [paolotremadio/homebridge-automation-delayed-trigger#1]
The plugin is not working correctly for me. 

From Description
========
When the timer ends, the sensor will detect a movement    **<<<< Working** 
and the switch will turn off.     **<<<< Not Working**
Turning off the switch will stop the timer.    **<<<< Working** 

My Config
========
        {
            "accessory": "AutomationDelayedTrigger",
            "name": "Bellas Home",
            "delay": 10000
        },
        {
            "accessory": "AutomationDelayedTrigger",
            "name": "1 Disable Bellas Home",
            "delay": 3000
        },
        {
            "accessory": "AutomationDelayedTrigger",
            "name": "2 Disable Bellas Home",
            "delay": 8000
        },

I get switches and sensors in Home. The timer switch and motion sensor appear to work but the switch does not turn off when the timer expires. I've tried updating the configuration, restarting homebridge, restarting my raspberrypi. No change.

Homebridge Version 0.4.38
tvOS 11.3

**Comment by paolotremadio** [comment]
Hi, you're right. That was a mistake in the readme. The switch does not turn itself off. I think it is ok. Turning off the switch will stop the movement from being detected.

**Comment by tkundhi** [comment]
Thanks for the clarification. I already had an automation created to reset when the sensor detected motion.
