### ISSUE TITLE
Max Delay Time

### ISSUE THREAD

**Issue by Nastras** [paolotremadio/homebridge-automation-delayed-trigger#2]
Hello, can you tell me what the maximum delay time is that can be set with your plugin?

Thank you!

**Comment by paolotremadio** [comment]
Hi. There’s no max. The plugin will honour the timeout as long as homebridge is not restarted. What delay are you planning to use?

**Comment by Nastras** [comment]
Thanks for the quick answer. I need a delay of 10 hours. Unfortunately, Apple's option in HomeKit does not work reliably at this time.

Do you think I can do it with your plugin?

**Comment by paolotremadio** [comment]
Yes, it should not be a problem.  Keep in mind that the plugin does not persist the timeout on disk. 10 hours is not a problem, as long as the homebridge instance does not restart. I think the max timeout possible might be around 24 days. So all good to go.

**Comment by Nastras** [comment]
That sounds good. I also thought about the Persist thing. My Homebridge automatically restarts every night which makes my project difficult.

Would it be maybe possible for you to install a Persist function?

**Comment by paolotremadio** [comment]
Yes. But I’m not sure it would be the best use for your scenario. What does your automation look like?

**Comment by Nastras** [comment]
Switch on battery charger Wait 10 hours, Switch off battery charger.

Operation should be possible via a hardware switch or home app directly on the device.

However, it should always run 10 hours.
